# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChJqyInTqbRpqwlJXK1APm0h7H8O08oC

#Installment and read data
"""

!pip install gspread oauth2client

from google.colab import files
uploaded = files.upload()

import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd

# Setup scope dan kredensial
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

creds = ServiceAccountCredentials.from_json_keyfile_name("colab-service-account.json", scope)
client = gspread.authorize(creds)

def read_sheet(spreadsheet_id, gid=None, sheet_name=None):
    """Baca sheet berdasarkan gid ATAU nama sheet."""
    if sheet_name:
        ws = client.open_by_key(spreadsheet_id).worksheet(sheet_name)
    elif gid:
        ws = client.open_by_key(spreadsheet_id).get_worksheet_by_id(int(gid))
    else:
        ws = client.open_by_key(spreadsheet_id).sheet1  # default ke sheet pertama

    data = ws.get_all_records()
    return pd.DataFrame(data)

import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

pd.set_option('display.max_columns', 100)

"""#Show data"""

sheet1_id = "18fJ2U96koMRctfbhybT1HsT2D95wgafLQMzlb-AwTvE"
df_sheet1 = read_sheet(sheet1_id)  # Reads the first sheet by default if sheet_name or gid is not provided
print("Sheet 1:")
df_sheet1.head()

"""#Data type"""

df_sheet1.info()

"""#Check Missing Value"""

# Total missing values per kolom
df_sheet1.isnull().sum()

df_sheet1.duplicated().sum()

df_sheet1.nunique()

# Contoh lihat isi kategori tertentu
for col in ['Product', 'Kategori', 'Domisili', 'Channel']:
    print(f"\nUnique in {col}:")
    print(df_sheet1[col].unique())

df_sheet1.describe()

"""#Check Categorical Column"""

categorical_cols = df_sheet1.select_dtypes(include='object').columns

for col in categorical_cols:
    print(f"\nValue counts for {col}:")
    print(df_sheet1[col].value_counts().head(10))

"""#Convert Tanggal Gabungan Column data type"""

# Convert to datetime
df_sheet1['Tanggal Gabungan'] = pd.to_datetime(df_sheet1['Tanggal Gabungan'], errors='coerce')

# Cek hasil
df_sheet1['Tanggal Gabungan'].head()

"""#Handling missing values"""

long_text_cols = [
    'Alasan mengambil kategori Bootcamp',
    'Motivasi mengikuti bootcamp',
    'Catatan'
]
# ambil semua kolom object (categorical)
cat_cols = df_sheet1.select_dtypes(include='object').columns

# kolom yang harus diisi Unknown
cols_to_fill = [c for c in cat_cols if c not in long_text_cols]

# isi dengan Unknown untuk string kosong
df_sheet1[cols_to_fill] = df_sheet1[cols_to_fill].replace('', 'Unknown')

# kolom teks panjang → ubah '' menjadi NaN
df_sheet1[long_text_cols] = df_sheet1[long_text_cols].replace('', np.nan)

"""#Handling cleaning text"""

for col in cat_cols:
    df_sheet1[col] = df_sheet1[col].astype(str).str.strip().str.lower()

for col in cols_to_fill:
    df_sheet1[col] = df_sheet1[col].str.title()

df_sheet1.groupby(['Provinsi'])['Kota'].nunique().sort_values(ascending=False)
df_sheet1['Kota(Jabodetabek)'].value_counts()

print(df_sheet1['Tahun'].unique())
print(df_sheet1['Bulan'].unique())
print(df_sheet1['Hari'].describe())

df_sheet1[['Hari']].boxplot()

df_sheet1['Tanggal Gabungan'].isnull().sum()

map_channel = {
    'Ig': 'Instagram',
    'Instagram Ads': 'Instagram',
    'Instagram Ad': 'Instagram',
    'Google Ads': 'Google',
    'Google Ad': 'Google',
    'Refferal': 'Referral',
    'Unknown': 'Unknown'
}

df_sheet1['Channel'] = df_sheet1['Channel'].replace(map_channel)
df_sheet1['Dengar Dibimbing darimana'] = df_sheet1['Dengar Dibimbing darimana'].replace(map_channel)

import re

def extract_age(value):
    match = re.search(r'\d+', str(value))
    return int(match.group()) if match else np.nan

df_sheet1['Umur'] = df_sheet1['Umur'].apply(extract_age)

df_sheet1 = df_sheet1[(df_sheet1['Hari'] >= 1) & (df_sheet1['Hari'] <= 31)]

df_sheet1 = df_sheet1[(df_sheet1['Tahun'] >= 2020) & (df_sheet1['Tahun'] <= 2030)]

df_sheet1 = df_sheet1.drop_duplicates()
df_sheet1.shape

"""#Analyze Tanggal Gabungan Column is missing"""

invalid_dates = df_sheet1[df_sheet1['Tanggal Gabungan'].isnull()]
invalid_dates[['Sumber Sheet', 'Tanggal Gabungan']].head(20)

df_sheet1['Tanggal Gabungan'] = pd.to_datetime(
    df_sheet1['Tanggal Gabungan'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

df_sheet1['Tanggal Gabungan_fix'] = pd.to_datetime(
    df_sheet1[['Tahun', 'Bulan', 'Hari']].astype(str).agg('-'.join, axis=1),
    errors='coerce'
)

invalid_dates = df_sheet1[df_sheet1['Tanggal Gabungan_fix'].isnull()]
invalid_dates[['Sumber Sheet', 'Tanggal Gabungan_fix']].head(20)

df_sheet1['Bulan'].unique()

bulan_map = {
    'jan': '01', 'januari': '01', 'january': '01',
    'feb': '02', 'februari': '02', 'february': '02',
    'mar': '03', 'maret': '03', 'march': '03',
    'apr': '04', 'april': '04',
    'mei': '05', 'may': '05',
    'jun': '06', 'juni': '06', 'june': '06',
    'jul': '07', 'juli': '07', 'july': '07',
    'agu': '08', 'agustus': '08', 'august': '08',
    'sep': '09', 'september': '09',
    'okt': '10', 'oktober': '10', 'october': '10',
    'nov': '11', 'november': '11',
    'des': '12', 'desember': '12', 'december': '12'
}

df_sheet1['Bulan_fix'] = df_sheet1['Bulan'].str.lower().map(bulan_map)

df_sheet1['Tanggal Gabungan_fix'] = pd.to_datetime(
    df_sheet1['Tahun'].astype(str) + '-' +
    df_sheet1['Bulan_fix'].astype(str) + '-' +
    df_sheet1['Hari'].astype(str),
    errors='coerce'
)

df_sheet1.info()

invalid_dates = df_sheet1[df_sheet1['Tanggal Gabungan_fix'].isnull()]
invalid_dates[['Sumber Sheet', 'Tanggal Gabungan_fix']].head(20)

df_sheet1[df_sheet1['Hari'].isnull() | (df_sheet1['Hari'] == 0)]

df_sheet1[df_sheet1['Bulan_fix'].isnull()]['Bulan'].unique()

df_sheet1[df_sheet1['Tahun'].isnull()]

bulan_map = {
    'jan': '01', 'januari': '01', 'january': '01',
    'feb': '02', 'februari': '02', 'february': '02',
    'mar': '03', 'maret': '03', 'march': '03',
    'apr': '04', 'april': '04',
    'mei': '05', 'may': '05',
    'jun': '06', 'juni': '06', 'june': '06',
    'jul': '07', 'juli': '07', 'july': '07',
    'agu': '08', 'agustus': '08', 'august': '08', 'ags': '08',
    'sep': '09', 'september': '09',
    'okt': '10', 'oktober': '10', 'october': '10',
    'nov': '11', 'november': '11',
    'des': '12', 'desember': '12', 'december': '12'
}

# 1. Mapping bulan ke angka
df_sheet1['Bulan_fix'] = df_sheet1['Bulan'].str.lower().map(bulan_map)

# 2. Buat tanggal gabungan baru
df_sheet1['Tanggal Gabungan_fix'] = pd.to_datetime(
    df_sheet1['Tahun'].astype(int).astype(str) + '-' +
    df_sheet1['Bulan_fix'].astype(str) + '-' +
    df_sheet1['Hari'].astype(int).astype(str),
    errors='coerce'
)

# 3. Cek masih ada NaT atau tidak
df_sheet1['Tanggal Gabungan_fix'].isna().sum()

df_sheet1.info()

"""#Cleaning Categorical Columns"""

location_cols = ['Domisili', 'Kota', 'Provinsi', 'Kota(Jabodetabek)', 'Negara']

for col in location_cols:
    df_sheet1[col] = df_sheet1[col].str.title()

bool_map = {
    'Ya': 'Yes', 'Iya': 'Yes', 'Yes': 'Yes', 'Y': 'Yes',
    'Tidak': 'No', 'No': 'No', 'N': 'No', 'Ga': 'No', 'Gak': 'No'
}

bool_cols = [
    'Pernah/Tidak memiliki pengalaman di bidang yang diambil',
    'Apakah memiliki skill bahasa inggris',
    'Penyaluran Kerja',
    'Pernah ikut acara dibimbing/tidak'
]

for col in bool_cols:
    df_sheet1[col] = df_sheet1[col].replace(bool_map)

"""#Handling Umur Column"""

df_sheet1['Umur'].isna().sum()

df_sheet1[df_sheet1['Umur'].isna()]

df_sheet1['Umur'] = df_sheet1['Umur'].astype('Int64')
df_sheet1['Umur'] = df_sheet1['Umur'].astype(str)

df_sheet1['Umur'] = df_sheet1['Umur'].apply(lambda x: 'Unknown' if x.lower() in ['nan', 'none', ''] else x)

df_sheet1['Umur'].value_counts(dropna=False)

df_sheet1.info()

df_sheet1.info()
df_sheet1.isnull().sum()
df_sheet1.head()

"""#EDA"""

df_sheet1.shape
df_sheet1.info()
df_sheet1.head()

def barplot_with_values(df_sheet1, column, title="", figsize=(25,6), rotate=45):
    counts = df_sheet1[column].value_counts()
    labels = counts.index
    values = counts.values

    # Highlight: warna pertama untuk max, warna kedua untuk lainnya
    colors = ['#ff5733' if v == values.max() else '#3498db' for v in values]

    plt.figure(figsize=figsize)
    bars = plt.bar(labels, values, color=colors)

    # Tambah label angka di atas bar
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval + 1,
                 f'{int(yval)}', ha='center', va='bottom', fontsize=10)

    plt.title(title, fontsize=14)
    plt.xticks(rotation=rotate)
    plt.ylabel("Jumlah")
    plt.tight_layout()
    plt.show()

"""##Product Distribution"""

barplot_with_values(df_sheet1, 'Product', "Jumlah Peserta per Product Bootcamp")

"""##Marketing Channel Distribution"""

barplot_with_values(df_sheet1, 'Channel', "Jumlah Peserta per Channel")

def lineplot_with_values(df_sheet1, date_col, title="", figsize=(12,5)):
    df_sheet1['Month_Only'] = df_sheet1[date_col].dt.to_period('M').astype(str)
    monthly = df_sheet1['Month_Only'].value_counts().sort_index()

    plt.figure(figsize=figsize)
    plt.plot(monthly.index, monthly.values, marker='o')

    # Highlight max value
    max_idx = monthly.values.argmax()
    plt.scatter(monthly.index[max_idx], monthly.values[max_idx],
                color='red', s=100, label="Peak")

    # Add values
    for i, val in enumerate(monthly.values):
        plt.text(monthly.index[i], val + 2, str(val), ha='center')

    plt.title(title)
    plt.xticks(rotation=45)
    plt.ylabel("Jumlah")
    plt.legend()
    plt.tight_layout()
    plt.show()

"""##Distribution of Students by Time (Trend)"""

lineplot_with_values(df_sheet1, 'Tanggal Gabungan_fix', "Trend Jumlah Peserta per Bulan")

"""Due to the high variability and free-text nature of the job category field, job statuses were grouped into high-level categories to provide a clearer overview of participant profiles."""

def simplify_job_category(x):
    x = str(x).lower()

    if 'job seeker' in x or 'fresh graduate' in x:
        return 'Job Seeker'
    elif 'mahasiswa' in x or 'student' in x:
        return 'Mahasiswa'
    elif 'freelance' in x or 'wirausaha' in x:
        return 'Freelance / Wirausaha'
    elif 'karyawan' in x or 'bekerja' in x or 'pegawai' in x:
        return 'Pekerja'
    else:
        return 'Others'

df_sheet1['Kategori_Pekerjaan_Simple'] = df_sheet1['Kategori Pekerjaan'].apply(simplify_job_category)

def hbarplot_with_values(df_sheet1, column, title="", figsize=(10,6)):
    counts = df_sheet1[column].value_counts()
    labels = counts.index
    values = counts.values

    colors = ['#ff5733' if v == values.max() else '#3498db' for v in values]

    plt.figure(figsize=figsize)
    bars = plt.barh(labels, values, color=colors)

    # Tambah text value
    for bar in bars:
        w = bar.get_width()
        plt.text(w + 1, bar.get_y() + bar.get_height()/2,
                 f'{int(w)}', va='center')

    plt.title(title)
    plt.xlabel("Jumlah")
    plt.tight_layout()
    plt.show()

"""##Distribution Employment Status"""

hbarplot_with_values(df_sheet1, 'Kategori_Pekerjaan_Simple', "Distribusi Kategori Pekerjaan")

"""##Distribution Education Status"""

hbarplot_with_values(df_sheet1, 'Level pendidikan', "Distribusi Level Pendidikan")

"""##Distribution Age Students"""

plt.figure(figsize=(8,5))
sns.histplot(df_sheet1['Umur'].dropna(), bins=20, kde=True)
plt.title("Distribusi Umur Peserta")
plt.tight_layout()
plt.show()

"""##Channel VS Product"""

top_channels = df_sheet1['Channel'].value_counts().head(5).index

df_sheet1['Channel_Simple'] = df_sheet1['Channel'].apply(
    lambda x: x if x in top_channels else 'Others'
)
top_products = df_sheet1['Product'].value_counts().head(6).index
df_top = df_sheet1[df_sheet1['Product'].isin(top_products)]
pivot = pd.crosstab(df_top['Product'], df_top['Channel_Simple'])

pivot_pct = pd.crosstab(
    df_top['Product'],
    df_top['Channel_Simple'],
    normalize='index'
) * 100

plt.figure(figsize=(12,6))
sns.countplot(
    data=df_sheet1,
    x='Product',
    hue='Channel_Simple'
)
plt.title("Distribusi Channel per Product (Top Channels + Others)")
plt.xticks(rotation=45)
plt.legend(bbox_to_anchor=(1,1))
plt.tight_layout()
plt.show()

"""###Channel Vs Product (Top 6)"""

plt.figure(figsize=(12,6))
sns.countplot(
    data=df_top,
    x='Product',
    hue='Channel_Simple'
)
plt.title("Distribusi Channel per Product (Top 6 Product)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

pivot.plot(
    kind='bar',
    stacked=True,
    figsize=(12,6)
)
plt.title("Distribusi Channel per Product (Stacked)")
plt.ylabel("Jumlah Peserta")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

pivot_pct.plot(
    kind='bar',
    stacked=True,
    figsize=(12,6)
)
plt.title("Proporsi Channel per Product (%)")
plt.ylabel("Persentase")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""##Product vs Job"""

pivot_job_status = pd.crosstab(df_sheet1['Product'], df_sheet1['Kategori_Pekerjaan_Simple'])
top_products = df_sheet1['Product'].value_counts().head(6).index
df_top_products_pivot = pivot_job_status[pivot_job_status.index.isin(top_products)]

df_top_products_pivot.plot(
    kind='bar',
    stacked=True,
    figsize=(12,6)
)

plt.title("Distribusi Status Pekerjaan per Product (Simplified)")
plt.ylabel("Jumlah Peserta")
plt.xticks(rotation=45)
plt.legend(title='Status Pekerjaan', bbox_to_anchor=(1,1))
plt.tight_layout()
plt.show()

"""Due to the free-text nature and high cardinality of the job category field, job statuses were grouped into high-level categories to improve interpretability during exploratory analysis

##Table Summary
"""

pd.crosstab(df_sheet1['Product'], df_sheet1['Channel'])

pd.crosstab(df_sheet1['Product'], df_sheet1['Channel'], normalize='index') * 100

"""#Deep Dive Analysis

###Product -> Channel
"""

prod_channel = (
    df_sheet1.groupby(['Product', 'Channel'])
      .size()
      .reset_index(name='count')
)

strong_channel_per_product = (
    prod_channel
    .sort_values(['Product', 'count'], ascending=[True, False])
    .groupby('Product')
    .head(1)
)

strong_channel_per_product

"""###Channel -> Product"""

channel_product = (
    df_sheet1.groupby(['Channel', 'Product'])
      .size()
      .reset_index(name='count')
)

dominant_product_per_channel = (
    channel_product
    .sort_values(['Channel', 'count'], ascending=[True, False])
    .groupby('Channel')
    .head(1)
)

dominant_product_per_channel

"""###Comparisson Share Product"""

overall_share = (
    df_sheet1['Product']
    .value_counts(normalize=True)
    .rename('overall_share')
)

meta_share = (
    df_sheet1[df_sheet1['Channel'] == 'Meta Ads']['Product']
    .value_counts(normalize=True)
    .rename('meta_ads_share')
)
share_comparison = pd.concat([overall_share, meta_share], axis=1)
share_comparison

"""###Meta Ads -> Data Science"""

meta_ds = df_sheet1[
    (df_sheet1['Channel'] == 'Meta Ads') &
    (df_sheet1['Product'] == 'Data Science')
]

meta_ds['Kategori_Pekerjaan_Simple'].value_counts()

df_sheet1[df_sheet1['Channel'] == 'Meta Ads'].groupby('Product')['Kategori_Pekerjaan_Simple'].value_counts()

meta_ds['Jurusan pendidikan'].value_counts().head(10)

meta_ds['Umur'].describe()

meta_ds['Motivasi mengikuti bootcamp'].dropna().head(10)

"""Analysis was conducted by first identifying the strongest channel for each product and the dominant product for each channel.
Product–channel relationships with significantly higher share compared to overall distribution were further analyzed to identify underlying demographic and motivational factors
"""

# Share product secara keseluruhan
overall_share = df_sheet1['Product'].value_counts(normalize=True) * 100

# Share product khusus Meta Ads
meta_share = (
    df_sheet1[df_sheet1['Channel'] == 'Meta Ads']['Product']
    .value_counts(normalize=True) * 100
)

share_compare = pd.concat([overall_share, meta_share], axis=1)
share_compare.columns = ['Overall %', 'Meta Ads %']
share_compare.sort_values('Meta Ads %', ascending=False)

meta = df_sheet1[df_sheet1['Channel'] == 'Meta Ads']
meta_ds = meta[meta['Product'] == 'Data Science']
meta_non_ds = meta[meta['Product'] != 'Data Science']

pd.crosstab(
    meta['Product'],
    meta['Kategori_Pekerjaan_Simple'],
    normalize='index'
) * 100

pd.crosstab(
    meta['Kategori_Pekerjaan_Simple'],
    meta['Product'] == 'Data Science',
    normalize='columns'
) * 100

meta_ds['Umur'].describe()
meta_non_ds['Umur'].describe()

plt.figure(figsize=(8,5))
sns.boxplot(
    data=meta,
    x=meta['Product'] == 'Data Science',
    y='Umur'
)
plt.xticks([0,1], ['Non Data Science', 'Data Science'])
plt.title("Distribusi Umur Meta Ads: Data Science vs Non-DS")
plt.tight_layout()
plt.show()

meta_ds['Jurusan pendidikan'].value_counts().head(10)

meta_non_ds['Jurusan pendidikan'].value_counts().head(10)

pd.crosstab(
    meta['Jurusan pendidikan'],
    meta['Product'] == 'Data Science',
    normalize='columns'
).sort_values(True, ascending=False).head(10) * 100

meta_ds['Motivasi mengikuti bootcamp'].dropna().head(10)

from collections import Counter
import re

text = " ".join(meta_ds['Motivasi mengikuti bootcamp'].dropna()).lower()
words = re.findall(r'\b[a-z]{4,}\b', text)

Counter(words).most_common(20)

text_non = " ".join(meta_non_ds['Motivasi mengikuti bootcamp'].dropna()).lower()
words_non = re.findall(r'\b[a-z]{4,}\b', text_non)

Counter(words_non).most_common(20)

# # filter dataset hanya Data Science
# ds = df_sheet1[df_sheet1['Product'] == "Data Science"]

# counts = ds['Channel'].value_counts()
# colors = ['#ff5733' if v == counts.max() else '#3498db' for v in counts.values]

# plt.figure(figsize=(10,5))
# bars = plt.bar(counts.index, counts.values, color=colors)

# # Tambahkan angka di atas bar
# for bar in bars:
#     yval = bar.get_height()
#     plt.text(bar.get_x() + bar.get_width()/2, yval + 1, str(int(yval)),
#              ha='center', va='bottom')

# plt.title("Persebaran Channel untuk Data Science (Dengan Highlight Max)")
# plt.xticks(rotation=45)
# plt.tight_layout()
# plt.show()

# # filter dataset hanya Data Science
# ds = df_sheet1[df_sheet1['Product'] == "Data Science"]

# counts = ds['Jurusan'].value_counts().head(15)
# colors = ['#ff5733' if v == counts.max() else '#3498db' for v in counts.values]

# plt.figure(figsize=(10,5))
# bars = plt.bar(counts.index, counts.values, color=colors)

# # Tambahkan angka di atas bar
# for bar in bars:
#     yval = bar.get_height()
#     plt.text(bar.get_x() + bar.get_width()/2, yval + 1, str(int(yval)),
#              ha='center', va='bottom')

# plt.title("Persebaran Tingkat Pendidikan untuk Data Science (Dengan Highlight Max)")
# plt.xticks(rotation=45)
# plt.tight_layout()
# plt.show()

# # filter dataset hanya Data Science
# ds = df_sheet1[df_sheet1['Product'] == "Data Science"]

# counts = ds['Kategori Pekerjaan'].value_counts().head(10)
# colors = ['#ff5733' if v == counts.max() else '#3498db' for v in counts.values]

# plt.figure(figsize=(10,5))
# bars = plt.bar(counts.index, counts.values, color=colors)

# # Tambahkan angka di atas bar
# for bar in bars:
#     yval = bar.get_height()
#     plt.text(bar.get_x() + bar.get_width()/2, yval + 1, str(int(yval)),
#              ha='center', va='bottom')

# plt.title("Persebaran Tingkat Pendidikan untuk Data Science (Dengan Highlight Max)")
# plt.xticks(rotation=45)
# plt.tight_layout()
# plt.show()

# # filter dataset hanya Data Science
# ds = df_sheet1[df_sheet1['Product'] == "Data Science"]

# counts = ds['Kota'].value_counts().head(10)
# colors = ['#ff5733' if v == counts.max() else '#3498db' for v in counts.values]

# plt.figure(figsize=(10,5))
# bars = plt.bar(counts.index, counts.values, color=colors)

# # Tambahkan angka di atas bar
# for bar in bars:
#     yval = bar.get_height()
#     plt.text(bar.get_x() + bar.get_width()/2, yval + 1, str(int(yval)),
#              ha='center', va='bottom')

# plt.title("Persebaran Tingkat Pendidikan untuk Data Science (Dengan Highlight Max)")
# plt.xticks(rotation=45)
# plt.tight_layout()
# plt.show()

# # filter dataset hanya Data Science
# ds = df_sheet1[df_sheet1['Product'] == "Human Resource"]

# counts = ds['Channel'].value_counts()
# colors = ['#ff5733' if v == counts.max() else '#3498db' for v in counts.values]

# plt.figure(figsize=(10,5))
# bars = plt.bar(counts.index, counts.values, color=colors)

# # Tambahkan angka di atas bar
# for bar in bars:
#     yval = bar.get_height()
#     plt.text(bar.get_x() + bar.get_width()/2, yval + 1, str(int(yval)),
#              ha='center', va='bottom')

# plt.title("Persebaran Channel untuk Human Resources (Dengan Highlight Max)")
# plt.xticks(rotation=45)
# plt.tight_layout()
# plt.show()

# filter dataset hanya Data Science
ds = df_sheet1[df_sheet1['Product'] == "Human Resource"]

counts = ds['Jurusan'].value_counts().head(15)
colors = ['#ff5733' if v == counts.max() else '#3498db' for v in counts.values]

plt.figure(figsize=(15,5))
bars = plt.bar(counts.index, counts.values, color=colors)

# Tambahkan angka di atas bar
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 1, str(int(yval)),
             ha='center', va='bottom')

plt.title("Persebaran Tingkat Pendidikan untuk Human Resource (Dengan Highlight Max)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# filter dataset hanya Data Science
ds = df_sheet1[df_sheet1['Product'] == "Human Resource"]

counts = ds['Kategori Pekerjaan'].value_counts().head(10)
colors = ['#ff5733' if v == counts.max() else '#3498db' for v in counts.values]

plt.figure(figsize=(10,5))
bars = plt.bar(counts.index, counts.values, color=colors)

# Tambahkan angka di atas bar
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 1, str(int(yval)),
             ha='center', va='bottom')

plt.title("Persebaran Tingkat Pendidikan untuk Human Resource (Dengan Highlight Max)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# filter dataset hanya Data Science
ds = df_sheet1[df_sheet1['Product'] == "Human Resource"]

counts = ds['Kota'].value_counts().head(10)
colors = ['#ff5733' if v == counts.max() else '#3498db' for v in counts.values]

plt.figure(figsize=(10,5))
bars = plt.bar(counts.index, counts.values, color=colors)

# Tambahkan angka di atas bar
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 1, str(int(yval)),
             ha='center', va='bottom')

plt.title("Persebaran Tingkat Pendidikan untuk Human Resource (Dengan Highlight Max)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# filter dataset hanya Data Science
ds = df_sheet1[df_sheet1['Product'] == "Digital Marketing"]

counts = ds['Channel'].value_counts()
colors = ['#ff5733' if v == counts.max() else '#3498db' for v in counts.values]

plt.figure(figsize=(10,5))
bars = plt.bar(counts.index, counts.values, color=colors)

# Tambahkan angka di atas bar
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 1, str(int(yval)),
             ha='center', va='bottom')

plt.title("Persebaran Channel untuk Digital Marketing (Dengan Highlight Max)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# filter dataset hanya Data Science
ds = df_sheet1[df_sheet1['Product'] == "Digital Marketing"]

counts = ds['Jurusan'].value_counts().head(15)
colors = ['#ff5733' if v == counts.max() else '#3498db' for v in counts.values]

plt.figure(figsize=(15,5))
bars = plt.bar(counts.index, counts.values, color=colors)

# Tambahkan angka di atas bar
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 1, str(int(yval)),
             ha='center', va='bottom')

plt.title("Persebaran Tingkat Pendidikan untuk Digital Marketing (Dengan Highlight Max)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# filter dataset hanya Data Science
ds = df_sheet1[df_sheet1['Product'] == "Digital Marketing"]

counts = ds['Kategori Pekerjaan'].value_counts().head(10)
colors = ['#ff5733' if v == counts.max() else '#3498db' for v in counts.values]

plt.figure(figsize=(10,5))
bars = plt.bar(counts.index, counts.values, color=colors)

# Tambahkan angka di atas bar
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 1, str(int(yval)),
             ha='center', va='bottom')

plt.title("Persebaran Kategori Pekerjaan untuk Digital Marketing (Dengan Highlight Max)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# filter dataset hanya Data Science
ds = df_sheet1[df_sheet1['Product'] == "Digital Marketing"]

counts = ds['Kota'].value_counts().head(10)
colors = ['#ff5733' if v == counts.max() else '#3498db' for v in counts.values]

plt.figure(figsize=(10,5))
bars = plt.bar(counts.index, counts.values, color=colors)

# Tambahkan angka di atas bar
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 1, str(int(yval)),
             ha='center', va='bottom')

plt.title("Persebaran Kota untuk Digital Marketing2 (Dengan Highlight Max)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

barplot_with_values(df_sheet1, 'Channel', "Distribusi Channel Marketing")

def barplot_product_per_channel(df_sheet1, channel_name, figsize=(25,6), rotate=45):
    plt.figure(figsize=figsize)
    df_channel = df_sheet1[df_sheet1['Channel'] == channel_name]
    counts = df_channel['Product'].value_counts()

    # Highlight bar tertinggi
    colors = ['#ff5733' if v == counts.max() else '#3498db' for v in counts.values]

    bars = plt.bar(counts.index, counts.values, color=colors)

    # Tambahkan angka di atas bar
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval + 1,
                 str(int(yval)), ha='center', va='bottom', fontsize=10)

    plt.title(f"Distribusi Product untuk Channel: {channel_name}",fontsize=14)
    plt.xticks(rotation=rotate)
    plt.ylabel("Jumlah Peserta")
    plt.tight_layout()
    plt.show()

barplot_product_per_channel(df_sheet1, "Meta Ads")

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

meta = df_sheet1[df_sheet1['Channel'] == "Meta Ads"]

meta.groupby('Product')['Jurusan pendidikan'].value_counts()

meta.groupby('Product')['Kategori Pekerjaan'].value_counts()

text_ds_meta = " ".join(
    meta[meta['Product']=="Data Science"]['Motivasi mengikuti bootcamp'].dropna()
)
print(text_ds_meta[:500])  # cek teks mentah

text_other = " ".join(
    meta[meta['Product']!="Data Science"]['Motivasi mengikuti bootcamp'].dropna()
)

sns.boxplot(data=meta, x='Product', y='Umur')

overall = df_sheet1['Product'].value_counts(normalize=True) * 100
meta_only = meta['Product'].value_counts(normalize=True) * 100

comparison = pd.concat([overall, meta_only], axis=1)
comparison.columns = ["Overall %", "Meta Ads %"]
comparison

meta[meta['Product']=="Data Science"]['Jurusan pendidikan'].value_counts().head(10)

top_kota = df_sheet1['Kota'].value_counts().head(10)
barplot_with_values(df_sheet1[df_sheet1['Kota'].isin(top_kota.index)], 'Kota', "Top 10 Kota Asal Peserta")

def boxplot_with_mean(df_sheet1, x, y, title="", figsize=(30,5)):
    plt.figure(figsize=figsize)
    sns.boxplot(data=df_sheet1, x=x, y=y)

    # Hitung mean dan tampilkan
    means = df_sheet1.groupby(x)[y].mean()

    for i, m in enumerate(means):
        plt.text(i, m, f"{m:.1f}", color='red', ha='center')

    plt.title(title)
    plt.xticks(rotation=45)
    plt.show()

!pip install wordcloud
from wordcloud import WordCloud

text_motivasi = " ".join(df_sheet1['Motivasi mengikuti bootcamp'].dropna().astype(str))

wordcloud = WordCloud(background_color="white", width=800, height=400).generate(text_motivasi)

plt.figure(figsize=(12,6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("WordCloud — Motivasi Mengikuti Bootcamp")
plt.show()

plt.figure(figsize=(25,6))
sns.countplot(data=df_sheet1, x='Product', hue='Channel')
plt.title("Distribusi Channel per Product Bootcamp")
plt.xticks(rotation=45)
plt.legend(title="Channel", bbox_to_anchor=(1,1))
plt.show()

plt.figure(figsize=(25,6))
sns.countplot(data=df_sheet1, x='Product', hue='Level pendidikan')
plt.title("Distribusi Pendidikan per Product Bootcamp")
plt.xticks(rotation=45)
plt.legend(title="Pendidikan", bbox_to_anchor=(1,1))
plt.show()

plt.figure(figsize=(6,4))
# Convert '<NA>' string to NaN before converting to float
df_sheet1['Umur'] = df_sheet1['Umur'].replace({'<NA>': np.nan}).astype(float)
corr = df_sheet1[['Umur', 'Hari', 'Tahun']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Heatmap Korelasi Numerik")
plt.show()

plt.figure(figsize=(25,5))
sns.boxplot(data=df_sheet1, x='Product', y='Umur', order=df_sheet1['Product'].value_counts().index)
plt.title("Distribusi Umur per Product Bootcamp")
plt.xticks(rotation=45)
plt.show()

channel_share = df_sheet1['Channel'].value_counts(normalize=True) * 100
channel_share

plt.figure(figsize=(20,20))
plt.pie(channel_share.values, labels=channel_share.index, autopct="%1.1f%%", startangle=45)
plt.title("Persentase Share Channel Marketing")
plt.show()

df_sheet1['Month_Only'] = df_sheet1['Tanggal Gabungan_fix'].dt.to_period('M').astype(str)

plt.figure(figsize=(12,6))
sns.countplot(data=df_sheet1, x='Month_Only', hue='Channel')
plt.title("Trend Channel Marketing per Bulan")
plt.xticks(rotation=45)
plt.legend(bbox_to_anchor=(1,1))
plt.tight_layout()
plt.show()

df_channel_product = df_sheet1.groupby('Product')['Channel'].agg(lambda x: x.value_counts().index[0])
df_channel_product

df_sheet1['channel_share'] = df_sheet1['Channel'].map(df_sheet1['Channel'].value_counts(normalize=True) * 100)
df_sheet1[['Channel', 'channel_share']].drop_duplicates().sort_values(by='channel_share', ascending=False)

pivot = pd.pivot_table(
    df_sheet1,
    index='Month_Only',
    columns='Channel',
    values='Product',
    aggfunc='count'
)

pivot

monthly = df_sheet1.groupby(['Month_Only', 'Channel']).size().reset_index(name='count')

plt.figure(figsize=(14,15))
sns.lineplot(data=monthly, x='Month_Only', y='count', hue='Channel', marker='o')
plt.title("Line Trend Channel per Bulan")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df_sheet1.to_csv('df_sheet1.csv', index=False)
from google.colab import files
files.download('df_sheet1.csv')